INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1101', UPPER('Iquique'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1107', UPPER('Alto Hospicio'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1401', UPPER('Pozo Almonte'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1402', UPPER('Camiña'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1403', UPPER('Colchane'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1404', UPPER('Huara'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('1405', UPPER('Pica'), '1', '1', '2');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2101', UPPER('Antofagasta'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2102', UPPER('Mejillones'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2103', UPPER('Sierra Gorda'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2104', UPPER('Taltal'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2201', UPPER('Calama'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2202', UPPER('Ollagüe'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2203', UPPER('San Pedro de Atacama'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2301', UPPER('Tocopilla'), '1', '2', '3');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('2302', UPPER('María Elena'), '1', '2', '3');		-- ################################################################################################################################################
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3101', UPPER('Copiapó'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3102', UPPER('Caldera'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3103', UPPER('Tierra Amarilla'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3201', UPPER('Chañaral'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3202', UPPER('Diego de Almagro'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3301', UPPER('Vallenar'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3302', UPPER('Alto del Carmen'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3303', UPPER('Freirina'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('3304', UPPER('Huasco'), '1', '3', '4');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4101', UPPER('La Serena'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4102', UPPER('Coquimbo'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4103', UPPER('Andacollo'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4104', UPPER('La Higuera'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4105', UPPER('Paiguano'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4106', UPPER('Vicuña'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4201', UPPER('Illapel'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4202', UPPER('Canela '), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4203', UPPER('Los Vilos'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4204', UPPER('Salamanca'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4301', UPPER('Ovalle'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4302', UPPER('Combarbalá'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4303', UPPER('Monte Patria'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4304', UPPER('Punitaqui'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('4305', UPPER('Río Hurtado'), '1', '4', '5');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5101', UPPER('Valparaíso'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5102', UPPER('Casablanca'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5103', UPPER('Concón'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5104', UPPER('Juan Fernández'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5105', UPPER('Puchuncaví'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5106', UPPER('Quilpué'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5107', UPPER('Quintero'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5108', UPPER('Villa Alemana'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5109', UPPER('Viña del Mar'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5201', UPPER('Isla  de Pascua'), '1', '5', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5301', UPPER('Los Andes'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5302', UPPER('Calle Larga'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5303', UPPER('Rinconada'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5304', UPPER('San Esteban'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5401', UPPER('La Ligua'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5402', UPPER('Cabildo'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5403', UPPER('Papudo'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5404', UPPER('Petorca'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5405', UPPER('Zapallar'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5501', UPPER('Quillota'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5502', UPPER('Calera'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5503', UPPER('Hijuelas'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5504', UPPER('La Cruz'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5505', UPPER('Limache'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5506', UPPER('Nogales'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5507', UPPER('Olmué'), '1', '5', '7');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5601', UPPER('San Antonio'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5602', UPPER('Algarrobo'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5603', UPPER('Cartagena'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5604', UPPER('El Quisco'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5605', UPPER('El Tabo'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5606', UPPER('Santo Domingo'), '1', '5', '6');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5701', UPPER('San Felipe'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5702', UPPER('Catemu'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5703', UPPER('Llaillay'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5704', UPPER('Panquehue'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5705', UPPER('Putaendo'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('5706', UPPER('Santa María'), '1', '5', '8');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6101', UPPER('Rancagua'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6102', UPPER('Codegua'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6103', UPPER('Coinco'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6104', UPPER('Coltauco'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6105', UPPER('Doñihue'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6106', UPPER('Graneros'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6107', UPPER('Las Cabras'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6108', UPPER('Machalí'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6109', UPPER('Malloa'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6110', UPPER('Mostazal'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6111', UPPER('Olivar'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6112', UPPER('Peumo'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6113', UPPER('Pichidegua'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6114', UPPER('Quinta de Tilcoco'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6115', UPPER('Rengo'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6116', UPPER('Requínoa'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6117', UPPER('San Vicente'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6201', UPPER('Pichilemu'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6202', UPPER('La Estrella'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6203', UPPER('Litueche'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6204', UPPER('Marchihue'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6205', UPPER('Navidad'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6206', UPPER('Paredones'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6301', UPPER('San Fernando'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6302', UPPER('Chépica'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6303', UPPER('Chimbarongo'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6304', UPPER('Lolol'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6305', UPPER('Nancagua'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6306', UPPER('Palmilla'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6307', UPPER('Peralillo'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6308', UPPER('Placilla'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6309', UPPER('Pumanque'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('6310', UPPER('Santa Cruz'), '1', '6', '15');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7101', UPPER('Talca '), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7102', UPPER('Constitución'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7103', UPPER('Curepto'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7104', UPPER('Empedrado'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7105', UPPER('Maule'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7106', UPPER('Pelarco'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7107', UPPER('Pencahue'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7108', UPPER('Río Claro'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7109', UPPER('San Clemente'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7110', UPPER('San Rafael'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7201', UPPER('Cauquenes'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7202', UPPER('Chanco'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7203', UPPER('Pelluhue'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7301', UPPER('Curicó'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7302', UPPER('Hualañé'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7303', UPPER('Licantén'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7304', UPPER('Molina'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7305', UPPER('Rauco'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7306', UPPER('Romeral'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7307', UPPER('Sagrada Familia'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7308', UPPER('Teno'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7309', UPPER('Vichuquén'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7401', UPPER('Linares'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7402', UPPER('Colbún'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7403', UPPER('Longaví'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7404', UPPER('Parral'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7405', UPPER('Retiro'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7406', UPPER('San Javier'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7407', UPPER('Villa Alegre'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('7408', UPPER('Yerbas Buenas'), '1', '7', '16');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8101', UPPER('Concepción'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8102', UPPER('Coronel'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8103', UPPER('Chiguayante'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8104', UPPER('Florida'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8105', UPPER('Hualqui'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8106', UPPER('Lota'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8107', UPPER('Penco'), '1', '8', '20');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8108', UPPER('San Pedro de la Paz'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8109', UPPER('Santa Juana'), '1', '8', '18');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8110', UPPER('Talcahuano'), '1', '8', '20');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8111', UPPER('Tomé'), '1', '8', '20');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8112', UPPER('Hualpén'), '1', '8', '20');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8201', UPPER('Lebu'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8202', UPPER('Arauco'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8203', UPPER('Cañete'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8204', UPPER('Contulmo'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8205', UPPER('Curanilahue'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8206', UPPER('Los Alamos'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8207', UPPER('Tirúa'), '1', '8', '19');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8301', UPPER('Los Angeles'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8302', UPPER('Antuco'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8303', UPPER('Cabrero'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8304', UPPER('Laja'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8305', UPPER('Mulchén'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8306', UPPER('Nacimiento'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8307', UPPER('Negrete'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8308', UPPER('Quilaco'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8309', UPPER('Quilleco'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8310', UPPER('San Rosendo'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8311', UPPER('Santa Bárbara'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8312', UPPER('Tucapel'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8313', UPPER('Yumbel'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8314', UPPER('Alto Biobío'), '1', '8', '21');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8401', UPPER('Chillán'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8402', UPPER('Bulnes'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8403', UPPER('Cobquecura'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8404', UPPER('Coelemu'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8405', UPPER('Coihueco'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8406', UPPER('Chillán Viejo'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8407', UPPER('El Carmen'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8408', UPPER('Ninhue'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8409', UPPER('Ñiquén'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8410', UPPER('Pemuco'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8411', UPPER('Pinto'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8412', UPPER('Portezuelo'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8413', UPPER('Quillón'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8414', UPPER('Quirihue'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8415', UPPER('Ránquil'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8416', UPPER('San Carlos'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8417', UPPER('San Fabián'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8418', UPPER('San Ignacio'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8419', UPPER('San Nicolás'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8420', UPPER('Treguaco'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('8421', UPPER('Yungay'), '1', '8', '17');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9101', UPPER('Temuco'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9102', UPPER('Carahue'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9103', UPPER('Cunco'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9104', UPPER('Curarrehue'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9105', UPPER('Freire'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9106', UPPER('Galvarino'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9107', UPPER('Gorbea'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9108', UPPER('Lautaro'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9109', UPPER('Loncoche'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9110', UPPER('Melipeuco'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9111', UPPER('Nueva Imperial'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9112', UPPER('Padre Las Casas'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9113', UPPER('Perquenco'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9114', UPPER('Pitrufquén'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9115', UPPER('Pucón'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9116', UPPER('Saavedra'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9117', UPPER('Teodoro Schmidt'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9118', UPPER('Toltén'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9119', UPPER('Vilcún'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9120', UPPER('Villarrica'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9121', UPPER('Cholchol'), '1', '9', '23');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9201', UPPER('Angol'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9202', UPPER('Collipulli'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9203', UPPER('Curacautín'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9204', UPPER('Ercilla'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9205', UPPER('Lonquimay'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9206', UPPER('Los Sauces'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9207', UPPER('Lumaco'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9208', UPPER('Purén'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9209', UPPER('Renaico'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9210', UPPER('Traiguén'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('9211', UPPER('Victoria'), '1', '9', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10101', UPPER('Puerto Montt'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10102', UPPER('Calbuco'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10103', UPPER('Cochamó'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10104', UPPER('Fresia'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10105', UPPER('Frutillar'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10106', UPPER('Los Muermos'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10107', UPPER('Llanquihue'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10108', UPPER('Maullín'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10109', UPPER('Puerto Varas'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10201', UPPER('Castro'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10202', UPPER('Ancud'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10203', UPPER('Chonchi'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10204', UPPER('Curaco de Vélez'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10205', UPPER('Dalcahue'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10206', UPPER('Puqueldón'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10207', UPPER('Queilén'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10208', UPPER('Quellón'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10209', UPPER('Quemchi'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10210', UPPER('Quinchao'), '1', '10', '27');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10301', UPPER('Osorno'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10302', UPPER('Puerto Octay'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10303', UPPER('Purranque'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10304', UPPER('Puyehue'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10305', UPPER('Río Negro'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10306', UPPER('San Juan de la Costa'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10307', UPPER('San Pablo'), '1', '10', '25');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10401', UPPER('Chaitén'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10402', UPPER('Futaleufú'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10403', UPPER('Huailaihué'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('10404', UPPER('Palena'), '1', '10', '26');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11101', UPPER('Coihaique'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11102', UPPER('Lago Verde'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11201', UPPER('Aisén'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11202', UPPER('Cisnes'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11203', UPPER('Guaitecas'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11301', UPPER('Cochrane'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11302', UPPER('OHiggins'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11303', UPPER('Tortel'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11401', UPPER('Chile Chico'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('11402', UPPER('Río Ibáñez'), '1', '11', '28');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12101', UPPER('Punta Arenas'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12102', UPPER('Laguna Blanca'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12103', UPPER('Río Verde'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12104', UPPER('San Gregorio'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12201', UPPER('Cabo de Hornos'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12202', UPPER('Antártica'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12301', UPPER('Porvenir'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12302', UPPER('Primavera'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12303', UPPER('Timaukel'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12401', UPPER('Natales'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('12402', UPPER('Torres del Paine'), '1', '12', '29');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13101', UPPER('Santiago'), '1', '13', '11');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13102', UPPER('Cerrillos'), '1', '13', '11');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13103', UPPER('Cerro Navia'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13104', UPPER('Conchalí'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13105', UPPER('El Bosque'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13106', UPPER('Estación Central'), '1', '13', '11');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13107', UPPER('Huechuraba'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13108', UPPER('Independencia'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13109', UPPER('La Cisterna'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13110', UPPER('La Florida'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13111', UPPER('La Granja'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13112', UPPER('La Pintana'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13113', UPPER('La Reina'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13114', UPPER('Las Condes'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13115', UPPER('Lo Barnechea'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13116', UPPER('Lo Espejo'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13117', UPPER('Lo Prado'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13118', UPPER('Macul'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13119', UPPER('Maipú'), '1', '13', '11');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13120', UPPER('Ñuñoa'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13121', UPPER('Pedro  Aguirre Cerda'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13122', UPPER('Peñalolén'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13123', UPPER('Providencia'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13124', UPPER('Pudahuel'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13125', UPPER('Quilicura'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13126', UPPER('Quinta Normal'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13127', UPPER('Recoleta'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13128', UPPER('Renca'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13129', UPPER('San Joaquín'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13130', UPPER('San Miguel'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13131', UPPER('San Ramón'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13132', UPPER('Vitacura'), '1', '13', '12');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13201', UPPER('Puente Alto'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13202', UPPER('Pirque'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13203', UPPER('San José de Maipo'), '1', '13', '14');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13301', UPPER('Colina'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13302', UPPER('Lampa'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13303', UPPER('Tiltil'), '1', '13', '9');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13401', UPPER('San Bernardo'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13402', UPPER('Buin'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13403', UPPER('Calera de Tango'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13404', UPPER('Paine'), '1', '13', '13');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13501', UPPER('Melipilla'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13502', UPPER('Alhué'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13503', UPPER('Curacaví'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13504', UPPER('María Pinto'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13505', UPPER('San Pedro'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13601', UPPER('Talagante'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13602', UPPER('El Monte'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13603', UPPER('Isla de Maipo'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13604', UPPER('Padre Hurtado'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('13605', UPPER('Peñaflor'), '1', '13', '10');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14101', UPPER('Valdivia'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14102', UPPER('Corral'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14103', UPPER('Lanco'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14104', UPPER('Los Lagos'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14105', UPPER('Máfil'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14106', UPPER('Mariquina'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14107', UPPER('Paillaco'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14108', UPPER('Panguipulli'), '1', '14', '24');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14201', UPPER('La Unión'), '1', '14', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14202', UPPER('Futrono'), '1', '14', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14203', UPPER('Lago Ranco'), '1', '14', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('14204', UPPER('Río Bueno'), '1', '14', '22');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('15101', UPPER('Arica'), '1', '15', '1');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('15102', UPPER('Camarones'), '1', '15', '1');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('15201', UPPER('Putre'), '1', '15', '1');
INSERT INTO comuna (codigo_comuna, comuna, nacionalidad_id, region_id, servicio_id) VALUES('15202', UPPER('General Lagos'), '1', '15', '1');