/* SERVICIO DE SALUD */
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(1, UPPER('Arica'), '15');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(2, UPPER('Iquique'), '1');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(3, UPPER('Antofagasta'), '2');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(4, UPPER('Atacama'), '3');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(5, UPPER('Coquimbo'), '4');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(6, UPPER('Valparaíso San Antonio'), '5');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(7, UPPER('Viña del Mar Quillota'), '5');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(8, UPPER('Aconcagua'), '5');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(9, UPPER('Metropolitano Norte'), '13');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(10, UPPER('Metropolitano Occidente'), '13');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(11, UPPER('Metropolitano Central'), '13');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(12, UPPER('Metropolitano Oriente'), '13');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(13, UPPER('Metropolitano Sur'), '13');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(14, UPPER('Metropolitano Sur Oriente'), '13');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(15, UPPER('Del Libertador B. O´Higgins'), '6');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(16, UPPER('Del Maule'), '7');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(17, UPPER('Ñuble'), '8');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(18, UPPER('Concepción'), '8');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(28, UPPER('Arauco'), '8');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(19, UPPER('Talcahuano'), '8');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(20, UPPER('Biobío'), '8');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(29, UPPER('Araucanía Norte'), '9');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(21, UPPER('Araucanía Sur'), '9');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(22, UPPER('Valdivia'), '14');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(23, UPPER('Osorno'), '10');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(24, UPPER('Del Reloncaví'), '10');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(33, UPPER('Chiloé'), '10');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(25, UPPER('Aisén'), '11');
INSERT INTO servicios_salud (id, servicio_salud, region_id) VALUES(26, UPPER('Magallanes'), '12');