/* COMUNA */
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1101', UPPER('Iquique'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1107', UPPER('Alto Hospicio'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1401', UPPER('Pozo Almonte'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1402', UPPER('Camiña'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1403', UPPER('Colchane'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1404', UPPER('Huara'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('1405', UPPER('Pica'), '1', '2');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2101', UPPER('Antofagasta'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2102', UPPER('Mejillones'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2103', UPPER('Sierra Gorda'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2104', UPPER('Taltal'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2201', UPPER('Calama'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2202', UPPER('Ollagüe'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2203', UPPER('San Pedro de Atacama'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2301', UPPER('Tocopilla'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('2302', UPPER('María Elena'), '2', '3');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3101', UPPER('Copiapó'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3102', UPPER('Caldera'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3103', UPPER('Tierra Amarilla'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3201', UPPER('Chañaral'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3202', UPPER('Diego de Almagro'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3301', UPPER('Vallenar'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3302', UPPER('Alto del Carmen'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3303', UPPER('Freirina'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('3304', UPPER('Huasco'), '3', '4');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4101', UPPER('La Serena'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4102', UPPER('Coquimbo'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4103', UPPER('Andacollo'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4104', UPPER('La Higuera'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4105', UPPER('Paiguano'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4106', UPPER('Vicuña'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4201', UPPER('Illapel'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4202', UPPER('Canela '), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4203', UPPER('Los Vilos'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4204', UPPER('Salamanca'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4301', UPPER('Ovalle'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4302', UPPER('Combarbalá'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4303', UPPER('Monte Patria'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4304', UPPER('Punitaqui'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('4305', UPPER('Río Hurtado'), '4', '5');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5101', UPPER('Valparaíso'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5102', UPPER('Casablanca'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5103', UPPER('Concón'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5104', UPPER('Juan Fernández'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5105', UPPER('Puchuncaví'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5801', UPPER('Quilpué'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5107', UPPER('Quintero'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5804', UPPER('Villa Alemana'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5109', UPPER('Viña del Mar'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5201', UPPER('Isla  de Pascua'), '5', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5301', UPPER('Los Andes'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5302', UPPER('Calle Larga'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5303', UPPER('Rinconada'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5304', UPPER('San Esteban'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5401', UPPER('La Ligua'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5402', UPPER('Cabildo'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5403', UPPER('Papudo'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5404', UPPER('Petorca'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5405', UPPER('Zapallar'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5501', UPPER('Quillota'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5502', UPPER('Calera'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5503', UPPER('Hijuelas'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5504', UPPER('La Cruz'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5802', UPPER('Limache'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5506', UPPER('Nogales'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5803', UPPER('Olmué'), '5', '7');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5601', UPPER('San Antonio'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5602', UPPER('Algarrobo'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5603', UPPER('Cartagena'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5604', UPPER('El Quisco'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5605', UPPER('El Tabo'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5606', UPPER('Santo Domingo'), '5', '6');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5701', UPPER('San Felipe'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5702', UPPER('Catemu'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5703', UPPER('Llaillay'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5704', UPPER('Panquehue'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5705', UPPER('Putaendo'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('5706', UPPER('Santa María'), '5', '8');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6101', UPPER('Rancagua'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6102', UPPER('Codegua'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6103', UPPER('Coinco'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6104', UPPER('Coltauco'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6105', UPPER('Doñihue'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6106', UPPER('Graneros'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6107', UPPER('Las Cabras'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6108', UPPER('Machalí'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6109', UPPER('Malloa'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6110', UPPER('Mostazal'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6111', UPPER('Olivar'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6112', UPPER('Peumo'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6113', UPPER('Pichidegua'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6114', UPPER('Quinta de Tilcoco'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6115', UPPER('Rengo'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6116', UPPER('Requínoa'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6117', UPPER('San Vicente'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6201', UPPER('Pichilemu'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6202', UPPER('La Estrella'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6203', UPPER('Litueche'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6204', UPPER('Marchihue'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6205', UPPER('Navidad'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6206', UPPER('Paredones'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6301', UPPER('San Fernando'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6302', UPPER('Chépica'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6303', UPPER('Chimbarongo'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6304', UPPER('Lolol'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6305', UPPER('Nancagua'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6306', UPPER('Palmilla'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6307', UPPER('Peralillo'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6308', UPPER('Placilla'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6309', UPPER('Pumanque'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('6310', UPPER('Santa Cruz'), '6', '15');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7101', UPPER('Talca '), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7102', UPPER('Constitución'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7103', UPPER('Curepto'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7104', UPPER('Empedrado'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7105', UPPER('Maule'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7106', UPPER('Pelarco'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7107', UPPER('Pencahue'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7108', UPPER('Río Claro'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7109', UPPER('San Clemente'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7110', UPPER('San Rafael'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7201', UPPER('Cauquenes'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7202', UPPER('Chanco'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7203', UPPER('Pelluhue'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7301', UPPER('Curicó'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7302', UPPER('Hualañé'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7303', UPPER('Licantén'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7304', UPPER('Molina'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7305', UPPER('Rauco'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7306', UPPER('Romeral'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7307', UPPER('Sagrada Familia'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7308', UPPER('Teno'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7309', UPPER('Vichuquén'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7401', UPPER('Linares'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7402', UPPER('Colbún'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7403', UPPER('Longaví'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7404', UPPER('Parral'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7405', UPPER('Retiro'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7406', UPPER('San Javier'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7407', UPPER('Villa Alegre'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('7408', UPPER('Yerbas Buenas'), '7', '16');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8101', UPPER('Concepción'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8102', UPPER('Coronel'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8103', UPPER('Chiguayante'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8104', UPPER('Florida'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8105', UPPER('Hualqui'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8106', UPPER('Lota'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8107', UPPER('Penco'), '8', '19');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8108', UPPER('San Pedro de la Paz'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8109', UPPER('Santa Juana'), '8', '18');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8110', UPPER('Talcahuano'), '8', '19');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8111', UPPER('Tomé'), '8', '19');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8112', UPPER('Hualpén'), '8', '19');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8201', UPPER('Lebu'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8202', UPPER('Arauco'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8203', UPPER('Cañete'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8204', UPPER('Contulmo'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8205', UPPER('Curanilahue'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8206', UPPER('Los Alamos'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8207', UPPER('Tirúa'), '8', '28');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8301', UPPER('Los Angeles'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8302', UPPER('Antuco'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8303', UPPER('Cabrero'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8304', UPPER('Laja'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8305', UPPER('Mulchén'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8306', UPPER('Nacimiento'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8307', UPPER('Negrete'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8308', UPPER('Quilaco'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8309', UPPER('Quilleco'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8310', UPPER('San Rosendo'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8311', UPPER('Santa Bárbara'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8312', UPPER('Tucapel'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8313', UPPER('Yumbel'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('8314', UPPER('Alto Biobío'), '8', '20');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16101', UPPER('Chillán'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16102', UPPER('Bulnes'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16202', UPPER('Cobquecura'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16203', UPPER('Coelemu'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16302', UPPER('Coihueco'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16103', UPPER('Chillán Viejo'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16104', UPPER('El Carmen'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16204', UPPER('Ninhue'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16303', UPPER('Ñiquén'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16105', UPPER('Pemuco'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16106', UPPER('Pinto'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16205', UPPER('Portezuelo'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16107', UPPER('Quillón'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16201', UPPER('Quirihue'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16206', UPPER('Ránquil'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16301', UPPER('San Carlos'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16304', UPPER('San Fabián'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16108', UPPER('San Ignacio'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16305', UPPER('San Nicolás'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16207', UPPER('Treguaco'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('16109', UPPER('Yungay'), '8', '17');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9101', UPPER('Temuco'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9102', UPPER('Carahue'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9103', UPPER('Cunco'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9104', UPPER('Curarrehue'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9105', UPPER('Freire'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9106', UPPER('Galvarino'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9107', UPPER('Gorbea'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9108', UPPER('Lautaro'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9109', UPPER('Loncoche'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9110', UPPER('Melipeuco'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9111', UPPER('Nueva Imperial'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9112', UPPER('Padre Las Casas'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9113', UPPER('Perquenco'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9114', UPPER('Pitrufquén'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9115', UPPER('Pucón'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9116', UPPER('Saavedra'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9117', UPPER('Teodoro Schmidt'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9118', UPPER('Toltén'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9119', UPPER('Vilcún'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9120', UPPER('Villarrica'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9121', UPPER('Cholchol'), '9', '21');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9201', UPPER('Angol'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9202', UPPER('Collipulli'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9203', UPPER('Curacautín'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9204', UPPER('Ercilla'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9205', UPPER('Lonquimay'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9206', UPPER('Los Sauces'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9207', UPPER('Lumaco'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9208', UPPER('Purén'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9209', UPPER('Renaico'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9210', UPPER('Traiguén'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('9211', UPPER('Victoria'), '9', '29');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10101', UPPER('Puerto Montt'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10102', UPPER('Calbuco'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10103', UPPER('Cochamó'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10104', UPPER('Fresia'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10105', UPPER('Frutillar'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10106', UPPER('Los Muermos'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10107', UPPER('Llanquihue'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10108', UPPER('Maullín'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10109', UPPER('Puerto Varas'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10201', UPPER('Castro'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10202', UPPER('Ancud'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10203', UPPER('Chonchi'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10204', UPPER('Curaco de Vélez'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10205', UPPER('Dalcahue'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10206', UPPER('Puqueldón'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10207', UPPER('Queilén'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10208', UPPER('Quellón'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10209', UPPER('Quemchi'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10210', UPPER('Quinchao'), '10', '33');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10301', UPPER('Osorno'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10302', UPPER('Puerto Octay'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10303', UPPER('Purranque'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10304', UPPER('Puyehue'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10305', UPPER('Río Negro'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10306', UPPER('San Juan de la Costa'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10307', UPPER('San Pablo'), '10', '23');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10401', UPPER('Chaitén'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10402', UPPER('Futaleufú'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10403', UPPER('Huailaihué'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('10404', UPPER('Palena'), '10', '24');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11101', UPPER('Coihaique'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11102', UPPER('Lago Verde'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11201', UPPER('Aisén'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11202', UPPER('Cisnes'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11203', UPPER('Guaitecas'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11301', UPPER('Cochrane'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11302', UPPER('OHiggins'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11303', UPPER('Tortel'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11401', UPPER('Chile Chico'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('11402', UPPER('Río Ibáñez'), '11', '25');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12101', UPPER('Punta Arenas'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12102', UPPER('Laguna Blanca'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12103', UPPER('Río Verde'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12104', UPPER('San Gregorio'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12201', UPPER('Cabo de Hornos'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12202', UPPER('Antártica'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12301', UPPER('Porvenir'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12302', UPPER('Primavera'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12303', UPPER('Timaukel'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12401', UPPER('Natales'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('12402', UPPER('Torres del Paine'), '12', '26');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13101', UPPER('Santiago'), '13', '11');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13102', UPPER('Cerrillos'), '13', '11');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13103', UPPER('Cerro Navia'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13104', UPPER('Conchalí'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13105', UPPER('El Bosque'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13106', UPPER('Estación Central'), '13', '11');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13107', UPPER('Huechuraba'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13108', UPPER('Independencia'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13109', UPPER('La Cisterna'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13110', UPPER('La Florida'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13111', UPPER('La Granja'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13112', UPPER('La Pintana'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13113', UPPER('La Reina'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13114', UPPER('Las Condes'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13115', UPPER('Lo Barnechea'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13116', UPPER('Lo Espejo'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13117', UPPER('Lo Prado'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13118', UPPER('Macul'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13119', UPPER('Maipú'), '13', '11');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13120', UPPER('Ñuñoa'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13121', UPPER('Pedro  Aguirre Cerda'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13122', UPPER('Peñalolén'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13123', UPPER('Providencia'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13124', UPPER('Pudahuel'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13125', UPPER('Quilicura'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13126', UPPER('Quinta Normal'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13127', UPPER('Recoleta'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13128', UPPER('Renca'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13129', UPPER('San Joaquín'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13130', UPPER('San Miguel'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13131', UPPER('San Ramón'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13132', UPPER('Vitacura'), '13', '12');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13201', UPPER('Puente Alto'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13202', UPPER('Pirque'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13203', UPPER('San José de Maipo'), '13', '14');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13301', UPPER('Colina'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13302', UPPER('Lampa'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13303', UPPER('Tiltil'), '13', '9');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13401', UPPER('San Bernardo'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13402', UPPER('Buin'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13403', UPPER('Calera de Tango'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13404', UPPER('Paine'), '13', '13');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13501', UPPER('Melipilla'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13502', UPPER('Alhué'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13503', UPPER('Curacaví'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13504', UPPER('María Pinto'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13505', UPPER('San Pedro'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13601', UPPER('Talagante'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13602', UPPER('El Monte'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13603', UPPER('Isla de Maipo'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13604', UPPER('Padre Hurtado'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('13605', UPPER('Peñaflor'), '13', '10');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14101', UPPER('Valdivia'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14102', UPPER('Corral'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14103', UPPER('Lanco'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14104', UPPER('Los Lagos'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14105', UPPER('Máfil'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14106', UPPER('Mariquina'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14107', UPPER('Paillaco'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14108', UPPER('Panguipulli'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14201', UPPER('La Unión'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14202', UPPER('Futrono'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14203', UPPER('Lago Ranco'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('14204', UPPER('Río Bueno'), '14', '22');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('15101', UPPER('Arica'), '15', '1');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('15102', UPPER('Camarones'), '15', '1');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('15201', UPPER('Putre'), '15', '1');
INSERT INTO comunas (codigo_comuna, comuna, region_id, servicio_salud_id) VALUES('15202', UPPER('General Lagos'), '15', '1');
